// Every word the page says, in one place.
//
// Add a language by adding a key here: the picker builds itself from whatever
// is in this object, and anything a pack leaves out falls back to Korean rather
// than showing a blank. Placeholders are {name} and are filled by fmt().
window.LANG = {

// ---------------------------------------------------------------- 한국어
ko: {
  name: "한국어",
  ui: {
    title: "초파리의 습격",
    subtitle: "초파리에게서 인류의 존엄을 보여주세요.",
    loading: "초파리를 내려받는 중…",
    brain: "뉴런 {n} · 간선 {e} · 학습되는 값 0개 · 브라우저에서 그대로 돈다 ({kb} KB)",
    start: "시작", running: "도는 중",
    difficulty: "난도", speed: "가속", picture: "그림",
    myPicture: "내 그림", language: "언어",
    you: "사람", fly: "초파리", flyEmoji: "초파리 🪰",
    home: "제자리", moves: "수", sec: "초",
    youTip: "끌어다 놓거나, 두 개를 눌러 바꾼다",
    youHint: "조각을 끌어다 놓으면 자리가 바뀐다",
    original: "원본", tapBig: "눌러서 크게",
    zoomTip: "아무 데나 눌러 닫기 · 시계는 계속 간다",
    ready: "준비…",
    hintIdle: "난도와 속도를 고르고 시작",
    hintPlay: "같은 그림, 같은 섞인 상태. 먼저 맞추면 이긴다.",
    scanning: "{k} / {of}장 보는 중",
    flyTip: "한 수에 {c}장 × {ms}ms",
    level: "{n}조각 · 최단 {best}수",
    speedReal: "실제",
    credit: '배선은 실제 초파리 뇌다 — <a href="https://male-cns.janelia.org/" ' +
            'target="_blank" rel="noopener">MaleCNS v1.0</a>, HHMI Janelia, CC BY 4.0. ' +
            "광수용체 4,512 + L1 1,767, 간선 7,107, 학습되는 값 0개.",
  },
  sizes: ["쉬움 · 6조각", "보통 · 12조각", "어려움 · 16조각",
          "아주 어려움 · 20조각", "지옥 · 30조각"],
  sizesShort: ["6조각", "12조각", "16조각", "20조각", "30조각"],
  howto: {
    title1: "어떻게 하는 건가",
    diaYou: "내 판", diaSwap: "바뀐다",
    rules1: [
      "<b>조각을 끌어다 놓으면</b> 놓은 자리와 바뀐다. 두 개를 차례로 눌러도 되고, 같은 조각을 다시 누르면 취소된다.",
      "<b>같은 그림, 같은 섞인 상태</b>로 초파리와 동시에 출발한다. 먼저 다 맞추는 쪽이 이긴다.",
      "<b>원본을 누르면</b> 크게 볼 수 있다. 시계는 그동안에도 간다.",
    ],
    more: "상대가 누구냐 ›", back: "‹ 돌아가기", skip: "다시 보지 않기",
    title2: "상대는 진짜 초파리 뇌다",
    rules2: [
      "MaleCNS v1.0 커넥톰에서 <b>광수용체 4,512개와 L1 1,767개</b>를 그대로 떼어 왔다. 간선 7,107개, <b>학습되는 값은 0개</b>다.",
      "한 수마다 가능한 교환을 전부 만들어 <b>한 장씩</b> 눈에 비춘다. {pace}",
      "속도를 초파리에 맞춘 이유: 실제 초파리는 뇌가 하나라 한 장면씩 보고, 광수용체에서 라미나까지 <b>12~22ms</b>가 걸린다. 안 묶으면 1초 안에 끝낸다.",
      '초파리가 하는 일은 <b>"완성본과 얼마나 닮았나"</b>를 재는 것뿐이다. 후보를 만들고 고르고 옮기는 건 바깥 코드가 한다.',
    ],
    pace: "지금은 {n}조각이라 한 수에 {c}장, 장당 {ms}ms 로 {sec}초 걸린다.",
    tally: "모든 플레이어 합계 — 사람 {h} : 초파리 {f}",
  },
  intro: {
    kicker: "인류 대 초파리",
    standing: "현재 전황",
    enter: "맞서기",
    // 대왕의 첫 인사. 지금 전황에 따라 고른다.
    none: ["아직 아무도 나를 막지 못했다. 네가 처음인가.",
           "이 별에서 나에게 도전한 자는 없다. 지금까지는.",
           "기록이 비어 있군. 네 이름을 첫 줄에 적어 주마."],
    ahead: ["나는 이미 {f}번 이겼다. 너는 몇 번째 도전자인가.",
            "인류는 {h}번 이겼다. 나는 {f}번이다. 계산은 네가 해라.",
            "{f}승. 그리고 오늘 하나가 더 늘 것이다.",
            "네 동족 {h}명이 나를 막았다. 나머지는 막지 못했다."],
    even:  ["{h} 대 {f}. 아직은 대등하다고 해 두자.",
            "팽팽하군. 오늘 네가 기울일 수 있겠나.",
            "{h} 대 {f}. 이 줄을 네가 당겨 보아라."],
    behind:["인류가 {h}번 이겼다. 인정한다. 오늘은 다르다.",
            "{h} 대 {f}. 방심했을 뿐이다.",
            "네 동족이 제법 버티고 있군. 너는 어떤가."],
  },
  over: { win: "이겼다", lose: "졌다", again: "다시 한 판",
          tallyHead: "모든 플레이어 합계" },
  lord: {
    win: [
      "인간이여. 너는 {t}조각 중 {n}개를 맞췄다.",
      "{n} / {t}. 이것이 너의 한계다.",
      "{t}개 중 {n}개. 기록해 두마.",
      "저항은 기록되었다. {t}조각 중 {n}개였다.",
      "손가락이 열 개인데 {n}개인가.",
      "이 별의 주인이 바뀌는 날이다. 너는 {n}개를 맞췄다.",
      "너희의 문명은 {t}분의 {n}에서 멈췄다.",
      "{n}개. 그것이 인류의 최선이었나.",
      "나는 눈이 하나다. 너는 {t}개 중 {n}개다.",
    ],
    lose: [
      "오늘은... 물러나겠다. 오늘은.",
      "방심했다. 단지 그뿐이다.",
      "이것으로 끝이라 생각하지 마라.",
      "인간 하나를 이기지 못했다고 세계가 바뀌지는 않는다.",
      "기억해 두마. 네 손가락 열 개를.",
      "재대결을 요구한다. 지금 당장.",
      "운이었다. 다음에는 운도 없을 것이다.",
      "나는 지치지 않는다. 너는 지친다.",
    ],
  },
  lines: {
    look: [
      "{seen}장째… 나는 서두르지 않는다.",
      "{of}장. 전부 본 뒤에 결정하겠다.",
      "이것인가… 아니면 저것인가…",
      "시간은 나의 편이다. 나는 지치지 않는다.",
      "한 장씩. 언제나 한 장씩.",
      "너희가 눈을 깜빡이는 사이에도 나는 보고 있다.",
      "인간은 서두르다 실수한다.",
      "이 판의 끝은 이미 정해져 있다.",
      "{seen}장을 보았다. 아직 {of}장까지 남았다.",
      "천천히. 아주 천천히.",
      "너의 손이 떨리는 것이 보인다.",
      "나에게는 밤낮이 없다.",
      "이 별의 모든 그림을 언젠가 다 볼 것이다.",
    ],
    good: [
      "보아라.", "이것이 순리다.", "계획대로다.", "한 걸음 가까워졌다.",
      "너의 패배가 한 칸 다가왔다.", "말했듯이.", "저항은 무의미하다.",
      "좁혀지고 있다.", "이것도 계산 안에 있었다.", "훌륭하군. 나 말이다.",
      "예정된 수순이다.",
    ],
    bad: [
      "…실수마저 계산에 넣었다.", "잠깐. 다시 보겠다.",
      "이것은 후퇴가 아니라 우회다.", "누구에게도 말하지 마라.",
      "못 본 것으로 하겠다.", "일시적 조정이다.",
      "이런 날도 있는 법이다.", "계획의 일부다. 믿어라.",
    ],
    ahead: [
      "느리구나, 인간.", "그 속도로 나를 막을 셈인가.", "이미 늦었다.",
      "손가락이 열 개인데 그것뿐인가.", "지켜보는 것도 지루하군.",
      "포기해도 좋다.", "네 종족 전체가 이 정도인가.",
    ],
    behind: [
      "잠깐. 이건 예정에 없다.", "제법이군. 인간치고는.",
      "아직 끝나지 않았다.", "운이 좋았을 뿐이다.",
      "…흥미롭군.", "일시적인 것이다.", "네 이름을 기억해 두겠다.",
    ],
    close: [
      "끝이 보인다.", "한 수만 더.", "이 판은 나의 것이다.",
      "마지막이다.", "준비는 되었나.",
    ],
    win: [
      "끝났다. 인간은 나의 것이다.", "설마 했지? 그 설마다.",
      "이 별의 주인이 바뀌었다.", "다음은 너의 이웃이다.",
    ],
    lose: [
      "오늘은 물러난다. 다음은 없다.", "방심했을 뿐이다.",
      "재대결을 요구한다.", "기억해 두마.",
    ],
  },
  tug: [
    [75, ["인류가 버티고 있다.", "대왕이 쫓겨나는 중.", "아직은 인간의 별이다.",
          "초파리, 본진까지 밀렸다.", "이 정도면 놀아준 것이다."]],
    [62, ["인간이 앞선다.", "전선은 아직 인간 쪽이다.", "밀어붙이는 중.",
          "대왕의 계획에 차질이 생겼다."]],
    [55, ["간신히 앞선다.", "한 발만 물러서면 뒤집힌다.",
          "이기고는 있는데 마음이 편하지 않다.", "아슬아슬하다."]],
    [46, ["팽팽하다.", "줄이 움직이지 않는다.", "반반. 이게 더 무섭다.",
          "인류와 초파리가 같은 힘으로 당기는 중."]],
    [38, ["밀리고 있다.", "줄이 저쪽으로 넘어갔다.", "전선이 무너지는 중.",
          "위태롭다."]],
    [25, ["인간은 초파리에게 패배하고 마는 건가...", "체면이 걸렸다.",
          "누가 좀 막아봐라.", "대왕이 줄을 끌고 간다."]],
    [0,  ["인류가 무너지는 중.", "초파리의 시대가 왔다.", "누가 좀 이겨주세요.",
          "인류 대표 구함.", "이 별의 주인이 바뀌었다."]],
  ],
  pictures: { shapes:"도형", tartan:"체크", waves:"물결",
              night:"밤하늘", glass:"스테인드글라스", mine:"내 그림" },
},

// ---------------------------------------------------------------- English
en: {
  name: "English",
  ui: {
    title: "Attack of the Fruit Fly",
    subtitle: "Defend the dignity of humankind.",
    loading: "Waking the fly…",
    brain: "{n} neurons · {e} edges · nothing trained · runs right here ({kb} KB)",
    start: "Start", running: "Playing",
    difficulty: "Size", speed: "Fly speed", picture: "Picture",
    myPicture: "My image", language: "Language",
    you: "You", fly: "Fly", flyEmoji: "Fly 🪰",
    home: "home", moves: "moves", sec: "s",
    youTip: "drag a piece, or tap two of them",
    youHint: "drag a piece onto another to swap them",
    original: "Original", tapBig: "tap to enlarge",
    zoomTip: "tap anywhere to close · the clock keeps running",
    ready: "Ready…",
    hintIdle: "pick a size and a speed, then start",
    hintPlay: "Same picture, same shuffle. First one finished wins.",
    scanning: "looked at {k} of {of}",
    flyTip: "{c} boards a move × {ms}ms",
    level: "{n} pieces · {best} moves at best",
    speedReal: "real",
    credit: 'The wiring is a real fly brain — <a href="https://male-cns.janelia.org/" ' +
            'target="_blank" rel="noopener">MaleCNS v1.0</a>, HHMI Janelia, CC BY 4.0. ' +
            "4,512 photoreceptors + 1,767 L1, 7,107 edges, nothing trained.",
  },
  sizes: ["Easy · 6 pieces", "Normal · 12 pieces", "Hard · 16 pieces",
          "Very hard · 20 pieces", "Hell · 30 pieces"],
  sizesShort: ["6", "12", "16", "20", "30"],
  howto: {
    title1: "How this works",
    diaYou: "your board", diaSwap: "swapped",
    rules1: [
      "<b>Drag a piece onto another</b> and they swap. Tapping two in turn does the same, and tapping the same piece again cancels it.",
      "<b>Same picture, same shuffle</b>, both of you at once. First one finished wins.",
      "<b>Tap the original</b> to see it big. The clock keeps running while you look.",
    ],
    more: "Who am I facing? ›", back: "‹ Back", skip: "Don't show this again",
    title2: "It really is a fly brain",
    rules2: [
      "<b>4,512 photoreceptors and 1,767 L1 cells</b> lifted straight out of the MaleCNS v1.0 connectome. 7,107 edges, <b>nothing trained</b>.",
      "Every move it builds every possible swap and looks at them <b>one at a time</b>. {pace}",
      "Why it is held to fly speed: a real fly has one brain and sees one scene at a time, and photoreceptor to lamina takes <b>12–22ms</b>. Unthrottled it finishes in under a second.",
      'All the fly does is report <b>how close a board looks to the finished picture</b>. Building the candidates, choosing and moving are this page’s work, not its.',
    ],
    pace: "At {n} pieces that is {c} boards a move, {ms}ms each, about {sec}s.",
    tally: "Everybody so far — humans {h} : fly {f}",
  },
  intro: {
    kicker: "Humans vs the fly",
    standing: "Where it stands",
    enter: "Face it",
    none: ["No one has stopped me yet. Will you be the first?",
           "Nobody on this planet has challenged me. So far.",
           "The record is empty. I will write your name on the first line."],
    ahead: ["I have won {f} times. Which challenger are you?",
            "Humans have {h}. I have {f}. You do the arithmetic.",
            "{f} wins. And one more before the day is out.",
            "{h} of your kind stopped me. The rest did not."],
    even:  ["{h} to {f}. Even, for now.",
            "Evenly matched. Can you tip it today?",
            "{h} to {f}. Pull the rope, then."],
    behind:["Humans have {h}. I concede it. Today is different.",
            "{h} to {f}. A lapse, nothing more.",
            "Your kind is holding. And you?"],
  },
  over: { win: "You win", lose: "You lose", again: "Again",
          tallyHead: "Everybody, added up" },
  lord: {
    win: [
      "Human. You placed {n} of {t}.",
      "{n} / {t}. That is your ceiling.",
      "{n} out of {t}. I will remember it.",
      "Your resistance is noted. {n} of {t}.",
      "Ten fingers, and {n} pieces.",
      "Today the planet changes hands. You managed {n}.",
      "Your civilisation stopped at {n} of {t}.",
      "{n}. Was that the best of your species?",
      "I have one eye. You have {n} of {t}.",
    ],
    lose: [
      "I withdraw. For today.",
      "A lapse. Nothing more.",
      "Do not mistake this for an ending.",
      "One human wins and you think the world turns.",
      "I will remember those ten fingers.",
      "I demand a rematch. Now.",
      "Luck. And luck runs out.",
      "I do not tire. You do.",
    ],
  },
  lines: {
    look: [
      "Board {seen}… I am in no hurry.",
      "{of} of them. I will decide when I have seen them all.",
      "This one… or that one…",
      "Time is on my side. I do not tire.",
      "One at a time. Always one at a time.",
      "I watch even while you blink.",
      "Humans rush. Rushing is how you lose.",
      "The end of this board is already decided.",
      "{seen} seen. {of} in all.",
      "Slowly. Very slowly.",
      "I can see your hand shaking.",
      "I have no night and no day.",
      "In time I will have seen every picture on this planet.",
    ],
    good: [
      "Observe.", "As it should be.", "According to plan.", "One step closer.",
      "Your defeat moves one square nearer.", "As I said.",
      "Resistance is pointless.", "The gap narrows.",
      "That too was accounted for.", "Magnificent. I mean me.",
      "Exactly as arranged.",
    ],
    bad: [
      "…even the error was accounted for.", "A moment. Let me look again.",
      "This is not a retreat. It is a detour.", "Tell no one.",
      "I saw nothing.", "A temporary adjustment.",
      "These days happen.", "Part of the plan. Trust me.",
    ],
    ahead: [
      "Slow, human.", "You mean to stop me at that pace?", "Too late already.",
      "Ten fingers, and that is all?", "Watching this is becoming dull.",
      "You may concede.", "Is this the whole of your species?",
    ],
    behind: [
      "Wait. This was not in the plan.", "Not bad. For a human.",
      "It is not over.", "Luck, nothing more.",
      "…interesting.", "A temporary thing.", "I will remember your name.",
    ],
    close: [
      "I can see the end.", "One more move.", "This board is mine.",
      "The last of it.", "Are you ready?",
    ],
    win: [
      "It is done. Humanity is mine.", "You doubted it. You were wrong.",
      "The planet has a new owner.", "Your neighbour is next.",
    ],
    lose: [
      "I withdraw today. There will not be another.", "A lapse, nothing more.",
      "I demand a rematch.", "I will remember.",
    ],
  },
  tug: [
    [75, ["Humanity is holding.", "The overlord is being driven out.",
          "Still a human planet.", "The fly is pushed back to its own ground.",
          "We were going easy on it."]],
    [62, ["Humans are ahead.", "The line still favours us.", "Pushing forward.",
          "The overlord's plan has hit a snag."]],
    [55, ["Barely ahead.", "One step back and it flips.",
          "Winning, and not enjoying it.", "Too close."]],
    [46, ["Dead even.", "The rope will not move.", "Half and half. That is worse.",
          "Humanity and one fly, pulling the same."]],
    [38, ["Losing ground.", "The rope has crossed over.", "The line is breaking.",
          "Precarious."]],
    [25, ["Will humanity really lose to a fly...", "There is pride at stake.",
          "Somebody stop it.", "The overlord is dragging the rope."]],
    [0,  ["Humanity is collapsing.", "The age of the fly has come.",
          "Somebody please win one.", "Champion of humanity wanted.",
          "The planet has a new owner."]],
  ],
  pictures: { shapes:"Shapes", tartan:"Tartan", waves:"Waves",
              night:"Night sky", glass:"Stained glass", mine:"My image" },
},

};
